# Generated by Django 2.2.2 on 2024-04-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真1'),
        ),
        migrations.AddField(
            model_name='message',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真2'),
        ),
    ]
