# Generated by Django 2.2.2 on 2024-04-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_auto_20240408_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='写真1'),
        ),
        migrations.AlterField(
            model_name='message',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='写真2'),
        ),
    ]
