# Generated by Django 3.2.1 on 2024-09-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_auto_20240922_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='aianswer',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
